# Generated by Django 3.2.9 on 2021-11-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
