# Generated by Django 3.2.9 on 2021-11-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
