# Generated by Django 3.2.9 on 2021-11-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211115_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.kycdocuments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered_bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.bankregistered'),
        ),
    ]
